baluproject/baluproject/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin


urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'baluproject.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', 'inventory.views.home_page'),
    url(r'^inventory/', include('inventory.urls')),
    url(r'^auth/', include('loginsys.urls')),
    url(r'^attributes/', include('attributes.urls')),
)

baluproject/loginsys/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'baluproject.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^login/', 'loginsys.views.login'),
    url(r'^logout/', 'loginsys.views.logout'),
    url(r'^register/', 'loginsys.views.register'),
)

baluproject/loginsys/views.py
# coding=utf-8
from django.shortcuts import render_to_response, redirect
from django.contrib import auth
from django.template import RequestContext
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.utils.translation import ugettext, ugettext_lazy as _
from django.core.context_processors import csrf

def login(request):
    args = {}
    args.update(csrf(request))
    if request.POST:
        username = request.POST.get('username', '')
        password = request.POST.get('password', '')
        #remember_me = request.POST.get('remember_me', '')
        user = auth.authenticate(username=username,password=password)
        if user is not None:
            if user.is_active:
                auth.login(request,user)
                return redirect('/')
            else:
                args['login_error'] = 'Пользователь не активен'
                return render_to_response("login.html",
                                          args,
                                          context_instance=RequestContext(request))
        else:
            args['login_error'] = 'Пользователь не найден, или пароль не верен'
            return render_to_response("login.html",
                                      args,
                                      context_instance=RequestContext(request))
    else:
        return render_to_response("login.html",
                                      context_instance=RequestContext(request))


def logout(request):
    auth.logout(request)
    return redirect('/')


class RegisterForm(UserCreationForm):

    username = forms.CharField(label=_("Логин"), max_length=30, error_messages={'required': 'Пожалуйста, введите Ваш логин.'})
    password1 = forms.CharField(label=_("Пароль"), max_length=30)
    password2 = forms.CharField(label=_("Повторите пароль"), max_length=30)
    email = forms.EmailField(label = _("Email"))
    first_name = forms.CharField(label = _("Имя"), required=False)
    last_name = forms.CharField(label = _("Фамилия"), required=False)

    class Meta:
        model = User
        fields = ("first_name", "last_name", "email", "username", "password1", "password2", )

    def save(self, commit=True):
        user = super(RegisterForm, self).save(commit=False)
        #user.username = self.cleaned_data.get("username")
        #user.password = self.cleaned_data.get("password1")
        user.email = self.cleaned_data.get("email")
        user.first_name = self.cleaned_data.get("first_name")
        user.last_name = self.cleaned_data.get("last_name")
        if commit:
            user.save()
        return user


def register(request):
    args = {}
    args.update(csrf(request))
    args['form'] = RegisterForm()
    if request.POST:
        newuser_form = RegisterForm(request.POST)
        if newuser_form.is_valid():
            # Save new user into DB
            newuser_form.save()
            # Authenticate user right here
            newuser = auth.authenticate(username=newuser_form.cleaned_data['username'],password=newuser_form.cleaned_data['password2'])
            return redirect('/')
        else:
            args['form'] = newuser_form
    return render_to_response("register.html",
                              args,
                              context_instance=RequestContext(request))

baluproject/loginsys/templates/login.html
{% extends "base.html" %}

{% block title %}Вход в систему{% endblock %}

{% block nav %}{% endblock %}

{% block content %}
    <form class="form-signin" role="form" action="/auth/login/" method="post">
    {% csrf_token %}
        <fieldset>
            <h2>Авторизация</h2>
            <hr class="colorgraph">
            <div class="form-group">
                <input type="text" name="username" id="username" class="form-control input-lg" placeholder="Имя пользователя">
            </div>
            <div class="form-group">
                <input type="password" name="password" id="password" class="form-control input-lg" placeholder="Пароль">
            </div>
            {% if login_error %}
                <div class="alert alert-warning alert-dismissible" role="alert">
                  <button type="button" class="close" data-dismiss="alert" aria-label="Закрыть"><span aria-hidden="true">&times;</span></button>
                  {{login_error}}
                </div>
            {% endif%}
            <span class="button-checkbox">
                <button type="button" class="btn" data-color="info">Запомните меня!</button>
                <input type="checkbox" name="remember_me" id="remember_me" checked="checked" class="hidden">
                <a href="" class="btn btn-link pull-right">Забыли пароль?</a>
            </span>
            <hr class="colorgraph">
            <div class="row">
                <div class="col-xs-6 col-sm-6 col-md-6">
                    <input type="submit" class="btn btn-lg btn-success btn-block" value="Войти">
                </div>
                <div class="col-xs-6 col-sm-6 col-md-6">
                    <a href="/auth/register/" class="btn btn-lg btn-primary btn-block">Register</a>
                </div>
            </div>
        </fieldset>
    </form>

{% endblock %}

baluproject/loginsys/templates/register.html
{% extends "base.html" %}

{% block title %}Регистрания нового пользователя{% endblock %}

{% block nav %}{% endblock %}

{% block content %}
<div class="row">
    <div class="col-xs-12 col-sm-8 col-md-6 col-sm-offset-2 col-md-offset-3">
		<form role="form"  action="/auth/register/" method="post">
			{% csrf_token %}
			<h2>Пожалуйста, зарегистрируйтесь</h2>
			<hr class="colorgraph">
			<div class="form-group">
				{{ form.non_field_errors }}
			</div>

			<div class="row">
				<div class="col-xs-12 col-sm-6 col-md-6">
					<div class="form-group">
                        <input type="text" name="first_name" id="id_first_name" class="form-control input-lg" placeholder="Имя" tabindex="1">
						{% if form.first_name.errors %}
							<div class="alert alert-warning alert-dismissible" role="alert">
							  <button type="button" class="close fade in" data-dismiss="alert" aria-label="Закрыть"><span aria-hidden="true">&times;</span></button>
								{% for error in form.first_name.errors %}
									{{ error|escape }}
								{% endfor %}
							</div>
						{% endif %}
					</div>
				</div>
				<div class="col-xs-12 col-sm-6 col-md-6">
					<div class="form-group">
						<input type="text" name="last_name" id="id_last_name" class="form-control input-lg" placeholder="Фамилия" tabindex="2">
						{% if form.last_name.errors %}
							<div class="alert alert-warning alert-dismissible" role="alert">
							  <button type="button" class="close fade in" data-dismiss="alert" aria-label="Закрыть"><span aria-hidden="true">&times;</span></button>
								{% for error in form.last_name.errors %}
									{{ error|escape }}
								{% endfor %}
							</div>
						{% endif %}
					</div>
				</div>
			</div>
			<div class="form-group">
				<input type="email" name="email" id="id_email" class="form-control input-lg" placeholder="Email" tabindex="3">
				{% if form.email.errors %}
					<div class="alert alert-warning alert-dismissible" role="alert">
					  <button type="button" class="close fade in" data-dismiss="alert" aria-label="Закрыть"><span aria-hidden="true">&times;</span></button>
						{% for error in form.email.errors %}
							{{ error|escape }}
						{% endfor %}
					</div>
				{% endif %}
			</div>
			<div class="form-group">
				<input type="text" name="username" id="id_username" class="form-control input-lg" placeholder="Логин"  value="{{ field.username }}" tabindex="4">
				{% if form.username.errors %}
					<div class="alert alert-warning alert-dismissible" role="alert">
					  <button type="button" class="close fade in" data-dismiss="alert" aria-label="Закрыть"><span aria-hidden="true">&times;</span></button>
						{% for error in form.username.errors %}
							{{ error|escape }}
						{% endfor %}
					</div>
				{% endif %}
			</div>
			<div class="row">
				<div class="col-xs-12 col-sm-6 col-md-6">
					<div class="form-group">
						<input type="password" name="password1" id="id_password1" class="form-control input-lg" placeholder="Пароль" value="{{ form.field.password1 }}" tabindex="5">
					</div>
				</div>
				<div class="col-xs-12 col-sm-6 col-md-6">
					<div class="form-group">
						<input type="password" name="password2" id="id_password2" class="form-control input-lg" placeholder="Повторите пароль" value="{{ form.field.password1 }}" tabindex="6">
					</div>
				</div>
				{% if form.password1.errors or form.password2.errors %}
				<div class="col-xs-12 col-sm-12 col-md-12">
					<div class="alert alert-warning alert-dismissible" role="alert">
					  <button type="button" class="close fade in" data-dismiss="alert" aria-label="Закрыть"><span aria-hidden="true">&times;</span></button>
						{% for error in form.password2.errors %}
							{{ error|escape }}
						{% endfor %}
					</div>
      			</div>
				{% endif %}
			</div>
			<div class="row">
				<div class="col-xs-4 col-sm-3 col-md-3">
					<span class="button-checkbox">
						<button type="button" class="btn" data-color="info" tabindex="7"> I Agree</button>
                        <input type="checkbox" name="t_and_c" id="t_and_c" class="hidden" value="1">
					</span>
				</div>
				<div class="col-xs-8 col-sm-9 col-md-9">
					 Нажимая кнопку <strong class="label label-primary">Регистрация</strong>, вы соглашаетесь с <a href="#" data-toggle="modal" data-target="#t_and_c_m">Terms and Conditions</a> нашего сервиса.
				</div>
			</div>

			<hr class="colorgraph">
			<div class="row">
				<div class="col-xs-12 col-md-6"><input type="submit" value="Регистрация" class="btn btn-primary btn-block btn-lg" tabindex="7"></div>
				<div class="col-xs-12 col-md-6"><a href="/auth/login/" class="btn btn-success btn-block btn-lg">Войти</a></div>
			</div>
		</form>
	</div>
</div>
<!-- Modal -->
<div class="modal fade" id="t_and_c_m" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog modal-lg">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
				<h4 class="modal-title" id="myModalLabel">Terms & Conditions</h4>
			</div>
			<div class="modal-body">
				<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Similique, itaque, modi, aliquam nostrum at sapiente consequuntur natus odio reiciendis perferendis rem nisi tempore possimus ipsa porro delectus quidem dolorem ad.</p>
				<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Similique, itaque, modi, aliquam nostrum at sapiente consequuntur natus odio reiciendis perferendis rem nisi tempore possimus ipsa porro delectus quidem dolorem ad.</p>
				<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Similique, itaque, modi, aliquam nostrum at sapiente consequuntur natus odio reiciendis perferendis rem nisi tempore possimus ipsa porro delectus quidem dolorem ad.</p>
				<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Similique, itaque, modi, aliquam nostrum at sapiente consequuntur natus odio reiciendis perferendis rem nisi tempore possimus ipsa porro delectus quidem dolorem ad.</p>
				<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Similique, itaque, modi, aliquam nostrum at sapiente consequuntur natus odio reiciendis perferendis rem nisi tempore possimus ipsa porro delectus quidem dolorem ad.</p>
				<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Similique, itaque, modi, aliquam nostrum at sapiente consequuntur natus odio reiciendis perferendis rem nisi tempore possimus ipsa porro delectus quidem dolorem ad.</p>
				<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Similique, itaque, modi, aliquam nostrum at sapiente consequuntur natus odio reiciendis perferendis rem nisi tempore possimus ipsa porro delectus quidem dolorem ad.</p>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-primary" data-dismiss="modal">I Agree</button>
			</div>
		</div><!-- /.modal-content -->
	</div><!-- /.modal-dialog -->
</div><!-- /.modal -->
{% endblock %}